### ISSUE TITLE
git_rev python version fails for me

### ISSUE THREAD

**Issue by bmaranville** [reductus/reductus#75]
(red3) bbm@offspec:~/dev/reductus/reflweb$ python3 server_flask.py
cacheargs: {'size_limit': 5000000000, 'shards': 5}
<string>:: (WARNING/2) No MathJax URL specified, using local fallback (see config.html)
<string>:: (WARNING/2) No MathJax URL specified, using local fallback (see config.html)
<string>:: (WARNING/2) No MathJax URL specified, using local fallback (see config.html)
<string>:: (WARNING/2) No MathJax URL specified, using local fallback (see config.html)
<string>:: (WARNING/2) No MathJax URL specified, using local fallback (see config.html)
<string>:: (WARNING/2) No MathJax URL specified, using local fallback (see config.html)
Traceback (most recent call last):
  File "server_flask.py", line 70, in <module>
    print_revision()
  File "/home/bbm/dev/reductus/dataflow/rev.py", line 93, in print_revision
    revision, timestamp = revision_info()
  File "/home/bbm/dev/reductus/dataflow/rev.py", line 118, in revision_info
    _REVISION_INFO = git_rev(repo_path())
  File "/home/bbm/dev/reductus/dataflow/rev.py", line 183, in git_rev
    with open(commit_ref, 'rb') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/home/bbm/dev/reductus/.git/objects/67/ca8de245983edd9cfbcb2d67752b26a527aa7e'

**Comment by bmaranville** [comment]
Maybe we should go back to using the git command through system calls.  If it was cloned from git, the command is guaranteed to exist, no?
